# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'grape'

gem 'airctiverecord', '~> 0.2.1'

gem 'dotenv', '~> 3.2'

gem 'zeitwerk', '~> 2.6'

gem 'rackup'

gem 'puma', '~> 7.1'

gem 'rack', '~> 3.2'

gem 'omniauth'
gem 'omniauth_openid_connect'
gem 'omniauth-oauth2'
gem 'rack-session'
gem 'faraday'
